-- Love2D Backend Demo for Argile
-- Uses portable ArgileDemoFrameForContext API

local ffi = require("ffi")

-- Load Argile FFI bindings (generated by build)
dofile("build/argile_api_ffi.lua")

ffi.cdef[[
void* malloc(size_t size);
void free(void* ptr);
]]

local argile = ffi.load("build/libargile.so")
local renderer = require("backends.love2d.renderer")

-- State
local arena_bytes = 256 * 1024 * 1024
local arena_mem
local ctx
local cmd_count = 0
local cmd_buffer = nil
local demo_ids = ffi.new("struct ArgileDemoIds")
local demo_focus = false
local demo_selected = false
local demo_disabled = false

-- String helper for FFI
local function mk_string(s)
    return ffi.new("struct String", {
        isStaticallyAllocated = true,
        length = #s,
        chars = ffi.cast("char*", s),
    })
end

function love.load()
    love.window.setTitle("Argile + Love2D Backend Demo")
    love.window.setMode(1280, 720, { resizable = true, vsync = 1 })

    -- Initialize Argile
    arena_mem = ffi.C.malloc(arena_bytes)
    if arena_mem == nil then
        error("malloc failed")
    end

    local arena = argile.CreateArenaWithCapacityAndMemory(arena_bytes, arena_mem)
    local dims = ffi.new("struct Dimensions", { width = 1280, height = 720 })
    ctx = argile.Initialize(arena, dims)
    if ctx == nil then
        error("Argile Initialize failed")
    end

    -- Verify API version
    local api_version = tonumber(argile.GetApiVersion())
    if api_version ~= tonumber(argile.ARGILE_API_VERSION) then
        error(("Argile API version mismatch: lib=%d expected=%d"):format(api_version, tonumber(argile.ARGILE_API_VERSION)))
    end

    -- Get demo element IDs for state toggling
    argile.ArgileDemoGetIds(demo_ids)
end

function love.update()
    local ww, hh = love.graphics.getDimensions()
    local mx, my = love.mouse.getPosition()
    local down = love.mouse.isDown(1)

    -- Build frame input struct
    local input = ffi.new("struct ArgileFrameInput")
    input.width = ww
    input.height = hh
    input.pointer_x = mx
    input.pointer_y = my
    input.pointer_down = down
    input.pointer_pressed = false  -- TODO: track pressed state
    input.pointer_released = false -- TODO: track released state
    input.scroll_delta_x = 0
    input.scroll_delta_y = 0
    input.delta_time = love.timer.getDelta()

    -- Set element states using portable API
    argile.SetElementFocusedForContext(ctx, demo_ids.card, demo_focus)
    argile.SetElementSelectedForContext(ctx, demo_ids.card, demo_selected)
    argile.SetElementDisabledForContext(ctx, demo_ids.card, demo_disabled)

    -- Call portable scene frame function
    cmd_count = tonumber(argile.ArgileDemoFrameForContext(ctx, input))
    cmd_buffer = argile.GetRenderCommandBufferForContext(ctx)
end

function love.draw()
    -- Clear background
    love.graphics.clear(0.06, 0.08, 0.12, 1.0)

    -- Render commands
    if cmd_buffer ~= nil then
        for i = 0, cmd_count - 1 do
            local cmd = cmd_buffer[i]
            local cmd_type = tonumber(cmd.commandType)
            
            if cmd_type == argile.RENDER_RECTANGLE then
                renderer.draw_rectangle(cmd)
            elseif cmd_type == argile.RENDER_BORDER then
                renderer.draw_border(cmd)
            elseif cmd_type == argile.RENDER_TEXT then
                renderer.draw_text(cmd)
            elseif cmd_type == argile.RENDER_PAINT then
                renderer.draw_paint(cmd, argile)
            end
            -- RENDER_CUSTOM and others are ignored
        end
    end

    -- Debug HUD
    love.graphics.setColor(1, 1, 1, 1)
    love.graphics.print(("Argile commands: %d"):format(cmd_count), 14, 12)
    love.graphics.print(("FPS: %d"):format(love.timer.getFPS()), 14, 30)
    love.graphics.print(("States: [F]ocus=%s [S]elected=%s [D]isabled=%s"):format(
        tostring(demo_focus), tostring(demo_selected), tostring(demo_disabled)
    ), 14, 48)
    love.graphics.print("Hover/click card for hover/active. Portable ArgileDemoFrameForContext()", 14, 66)
end

function love.keypressed(key)
    if key == "f" then
        demo_focus = not demo_focus
    elseif key == "s" then
        demo_selected = not demo_selected
    elseif key == "d" then
        demo_disabled = not demo_disabled
    elseif key == "r" then
        demo_focus = false
        demo_selected = false
        demo_disabled = false
    end
end

function love.quit()
    if arena_mem ~= nil then
        ffi.C.free(arena_mem)
        arena_mem = nil
    end
end
